FROM ultralytics/ultralytics
ARG YMIR="2.1.0"

ENV TORCH_NVCC_FLAGS="-Xfatbin -compress-all"
ENV LANG=C.UTF-8
ENV YMIR_VERSION=$YMIR
ENV YOLOV5_CONFIG_DIR='/app/data'

# Copy file from host to docker and install requirements
COPY . /app
RUN mkdir /img-man && mv /app/ymir/img-man/*.yaml /img-man/
RUN mv /app/models/*.ttf /root/.config/Ultralytics/

# install and requirements
RUN pip install .

# Download pretrained weight and font file
# v8
ADD https://github.com/ultralytics/assets/releases/download/v8.3.0/yolov8.pt /app
ADD https://github.com/ultralytics/assets/releases/download/v8.3.0/yolov8s.pt /app
ADD https://github.com/ultralytics/assets/releases/download/v8.3.0/yolov8m.pt /app
ADD https://github.com/ultralytics/assets/releases/download/v8.3.0/yolov8l.pt /app
ADD https://github.com/ultralytics/assets/releases/download/v8.3.0/yolov8n-seg.pt /app
ADD https://github.com/ultralytics/assets/releases/download/v8.3.0/yolov8s-seg.pt /app
ADD https://github.com/ultralytics/assets/releases/download/v8.3.0/yolov8m-seg.pt /app
ADD https://github.com/ultralytics/assets/releases/download/v8.3.0/yolov8l-seg.pt /app
ADD https://github.com/ultralytics/assets/releases/download/v8.3.0/yolov8n-pose.pt /app
ADD https://github.com/ultralytics/assets/releases/download/v8.3.0/yolov8s-pose.pt /app
ADD https://github.com/ultralytics/assets/releases/download/v8.3.0/yolov8m-pose.pt /app
ADD https://github.com/ultralytics/assets/releases/download/v8.3.0/yolov8l-pose.pt /app
ADD https://github.com/ultralytics/assets/releases/download/v8.3.0/yolov8n-obb.pt /app
ADD https://github.com/ultralytics/assets/releases/download/v8.3.0/yolov8s-obb.pt /app
ADD https://github.com/ultralytics/assets/releases/download/v8.3.0/yolov8m-obb.pt /app
ADD https://github.com/ultralytics/assets/releases/download/v8.3.0/yolov8l-obb.pt /app
# v10
ADD https://github.com/ultralytics/assets/releases/download/v8.3.0/yolov10n.pt /app
ADD https://github.com/ultralytics/assets/releases/download/v8.3.0/yolov10s.pt /app
ADD https://github.com/ultralytics/assets/releases/download/v8.3.0/yolov10m.pt /app
ADD https://github.com/ultralytics/assets/releases/download/v8.3.0/yolov10l.pt /app
# v11
ADD https://github.com/ultralytics/assets/releases/download/v8.3.0/yolo11n.pt /app
ADD https://github.com/ultralytics/assets/releases/download/v8.3.0/yolo11s.pt /app
ADD https://github.com/ultralytics/assets/releases/download/v8.3.0/yolo11m.pt /app
ADD https://github.com/ultralytics/assets/releases/download/v8.3.0/yolo11l.pt /app
ADD https://github.com/ultralytics/assets/releases/download/v8.3.0/yolo11n-seg.pt /app
ADD https://github.com/ultralytics/assets/releases/download/v8.3.0/yolo11s-seg.pt /app
ADD https://github.com/ultralytics/assets/releases/download/v8.3.0/yolo11m-seg.pt /app
ADD https://github.com/ultralytics/assets/releases/download/v8.3.0/yolo11l-seg.pt /app
ADD https://github.com/ultralytics/assets/releases/download/v8.3.0/yolo11n-pose.pt /app
ADD https://github.com/ultralytics/assets/releases/download/v8.3.0/yolo11s-pose.pt /app
ADD https://github.com/ultralytics/assets/releases/download/v8.3.0/yolo11m-pose.pt /app
ADD https://github.com/ultralytics/assets/releases/download/v8.3.0/yolo11l-pose.pt /app
ADD https://github.com/ultralytics/assets/releases/download/v8.3.0/yolo11n-obb.pt /app
ADD https://github.com/ultralytics/assets/releases/download/v8.3.0/yolo11s-obb.pt /app
ADD https://github.com/ultralytics/assets/releases/download/v8.3.0/yolo11m-obb.pt /app
ADD https://github.com/ultralytics/assets/releases/download/v8.3.0/yolo11l-obb.pt /app
ADD https://ultralytics.com/assets/Arial.ttf https://ultralytics.com/assets/Arial.Unicode.ttf /root/.config/Ultralytics/


# install ymir-exc sdk 2.1
RUN pip install "git+https://github.com/modelai/ymir-executor-sdk.git@ymir2.1.0"

# Make PYTHONPATH find local package
ENV PYTHONPATH=.
WORKDIR /app
RUN echo "python3 /app/ymir/start.py" > /usr/bin/start.sh
CMD bash /usr/bin/start.sh